import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — SnapCut AI" },
      { name: "description", content: "The terms governing your use of SnapCut AI." },
      { property: "og:url", content: "/terms" },
    ],
    links: [{ rel: "canonical", href: "/terms" }],
  }),
  component: Terms,
});

function Terms() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-16 prose prose-neutral">
      <div className="text-center md:text-left">
        <h1 className="text-4xl font-bold font-heading">Terms of Service</h1>
        <p className="mt-3 text-muted-foreground">Last updated: June 14, 2026</p>
      </div>

      <div className="mt-8 space-y-6">
        <Section title="1. Agreement to Terms">
          <p className="mt-2 text-muted-foreground leading-relaxed">
            By accessing or using SnapCut AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
          </p>
        </Section>

        <Section title="2. Account and Payments">
          <p className="mt-2 text-muted-foreground leading-relaxed">
            We offer both free credits and premium plans (Pro). 
            Payments are collected via the secure checkout system of our payment partner, **Razorpay**. 
            By purchasing the Pro plan (₹299/month), you agree to pay the fees and charges associated with your plan.
            Subscriptions are billed on a recurring monthly cycle unless cancelled. You may cancel at any time via your dashboard.
          </p>
        </Section>

        <Section title="3. Refund & Cancellation">
          <p className="mt-2 text-muted-foreground leading-relaxed">
            All purchases are subject to our Refund and Cancellation Policy. 
            Refunds must be requested within 7 days of the initial subscription purchase. 
            Refund requests for renewals are not eligible unless required by law.
          </p>
        </Section>

        <Section title="4. User Content & Ownership">
          <p className="mt-2 text-muted-foreground leading-relaxed">
            You retain all copyrights and intellectual property rights in the images you upload and the processed images generated by SnapCut AI. 
            You grant SnapCut AI a limited, non-exclusive license to process your images to deliver the Service.
          </p>
        </Section>

        <Section title="5. Acceptable Use">
          <p className="mt-2 text-muted-foreground leading-relaxed">
            You agree not to use the Service for any unlawful purpose, or to upload images containing material that is illegal, defamatory, harmful, or infringes on copyrights.
          </p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p className="mt-2 text-muted-foreground leading-relaxed">
            SnapCut AI is provided "as is" without warranties of any kind. 
            We shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our services.
          </p>
        </Section>
      </div>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="pt-4 border-t border-border/40">
      <h2 className="text-xl font-bold font-heading text-foreground">{title}</h2>
      <div className="mt-2">{children}</div>
    </div>
  );
}

